### ISSUE TITLE
MessageMapper.xml의 addMessage시 sql에러 발생

### ISSUE THREAD

**Issue by flzl2008** [Kosta179-final/MomsBay#38]
## 상황
- MessageMapper.xml에 ReceiveMessage를 add 하는 sql인 addReceiveMessage 을 작성하였다.
- 작성후 작동확인을 위해 Test Class인 MessageMapperTest 에 addReceiveMessage Test함수를 만들어 jUnit으로 실행함
- jUnit 결과로 org.springframework.jdbc.BadSqlGrammarException이 발생함

### 작성한 SQL
```
<insert id="addReceiveMessage" parameterType="receiveMessageVO">
		<selectKey order="BEFORE" resultType="int" keyProperty="receiveMessageNo">
			SELECT receive_message_seq.nextval FROM dual
		</selectKey>
		INSERT INTO receive_message(receive_message_no,title,content,regdate,send_id,receive_id)
		VALUES(${receiveMessageNo},${title},${content},sysdate,${memberVO.id},${receiveId})
</insert>
``` 

### 전달한 parameterType ReceiveMessageVO
```
@Data
@NoArgsConstructor
@AllArgsConstructor
public abstract class PostVO {
	private String title;
	private String content;
	private String regdate;
	private MemberVO memberVO;
}

@Data
@EqualsAndHashCode(callSuper=true)
@NoArgsConstructor
@AllArgsConstructor
public class ReceiveMessageVO extends PostVO{
	private int receiveMessageNo;
	private String receiveId;
	private boolean status;
}
```

### 실행을 위한 Test Class
```
@RunWith(SpringRunner.class)
@ContextConfiguration(locations= {"file:src/main/webapp/WEB-INF/spring-model.xml"})
public class MessageMapperTest {
	@Resource
	MessageMapper messageMapper;
	
	@Test
	public void addReceiveMessage() {
		ReceiveMessageVO receiveMessageVO=new ReceiveMessageVO();
		receiveMessageVO.setTitle("test");
		receiveMessageVO.setContent("testing");
		receiveMessageVO.setMemberVO(new MemberVO());
		receiveMessageVO.getMemberVO().setId("sys");
		receiveMessageVO.setReceiveId("java");
		messageMapper.addReceiveMessage(receiveMessageVO);
	}
}
```

### jUnit 실행결과
```
org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: ORA-00984: column not allowed here

### The error may exist in org/kosta/momsbay/model/mapper/MessageMapper.xml
### The error may involve org.kosta.momsbay.model.mapper.MessageMapper.addReceiveMessage-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO receive_message(receive_message_no,title,content,regdate,send_id,receive_id)   VALUES(15,test,testing,sysdate,sys,java)
### Cause: java.sql.SQLSyntaxErrorException: ORA-00984: column not allowed here

; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: ORA-00984: column not allowed here

	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy22.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:279)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:56)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy37.addReceiveMessage(Unknown Source)
	at org.kosta.momsbay.MessageMapperTest.addReceiveMessage(MessageMapperTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00984: column not allowed here

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:837)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:523)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1010)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1315)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3576)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3677)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1374)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 35 more

```

## 의문사항
- MessageMapper.xml에 작성한 addReceiveMessage의 sql에서 parameterType인 receiveMessageVO의 #{value}를 ''로 감싸면 정상 실행이 됨
- 지금까지의 Mybatis SQL에서 #{value}를 ''로 감싸지 않아도 실행이 됐는데 왜 이 경우에만 감싸면 되는지 의문이 생김

- mapper.xml에 정상실행되는 sql
```
<insert id="addReceiveMessage" parameterType="receiveMessageVO">
		<selectKey order="BEFORE" resultType="int" keyProperty="receiveMessageNo">
			SELECT receive_message_seq.nextval FROM dual
		</selectKey>
		INSERT INTO receive_message(receive_message_no,title,content,regdate,send_id,receive_id)
		VALUES(${receiveMessageNo},'${title}','${content}',sysdate,'${memberVO.id}','${receiveId}')
</insert>
```

**Comment by flzl2008** [comment]
## 해결

### 원인
- Mapper 안에 #{value}가 아닌 ${value}를 써서 Mybatis에서 parameter가 set이 안됨
- Mybatis안에서도 EL은 인식되므로 EL로 인식한 text값에 ""로 묶어줬을때 문자열로 인식하여 정상작동했었음

### 해결책
- Mapper 안에 sql에 $를 #으로 바꿔주면 된다.
